### ISSUE TITLE
Two-block protections not read correctly on 2.0.x

### ISSUE THREAD

**Issue by takatalvi** [megoesrawr/Modern-LWC#85] opened 2018-04-27 14:22 UTC
Hi, I posted this in the discussion on Spigot, but to be sure, I'll copy it here:

How are two-block protections handled? I thought there was a flag in the DB, but there is no such thing. Then I thought that maybe they are inserted as 2 separate protections, but no, it's just one protection ID. So there must be some automated way: when you click on one side of a double chest, the plugin checks the neighboring coordinates, or something. How can this be such a problem when updating to 2.0.5 from an older version? The plugin won't read my two-block protections correctly, and also for some reason omits half the signs. I can live with the signs, but the doors and double chests are a showstopper. I thought the initial load of the plugin would skim the DB and update it, or the updates would be separate for each protection upon opening, or the cleanup would take care of this, but no. You've done a great job since 2.0.0, but sadly, reading a pre-2.0.5 database is still an issue.

**Comment by Tsuser1** [comment] 2018-04-28 03:03
I just tried to replicate this on my local testing server and couldn't reproduce the issue. Are you using the latest public version (2.0.7)?

**Comment by takatalvi** [comment] 2018-04-28 10:03
2.0.7 was not out yet at the time then I submitted the bug, I'll have to try it out, thanks!

**Comment by takatalvi** [comment] 2018-04-28 10:37
I just tried it out, it seems to be the same. Two-block protections are broken, one half unprotected. After a cleanup and a few reloads/restarts, the plugin did not update the old protections but instead started removing them as corrupted. I made a test: two doors next to each other - one has the old lock from 1.9.4, the other one was destroyed, placed again, and locked on 2.0.7. Then I stopped the server, and opened the database to see what's the difference in the DB. I'm attaching a screenshot, the door with the old lock is red, the new one is green. Maybe there's a way to update the DB externally? Not sure.. However, now I see two protections for the same door (new, green), so I'm not sure what an external update of the DB would look like. Meanwhile I'm still on 1.9.4, this issue has time until MC 1.13 comes out :P
![untitled](https://user-images.githubusercontent.com/35687568/39395638-e772e500-4ae0-11e8-8ee8-a4e71662f2d4.png)

**Comment by takatalvi** [comment] 2018-04-30 11:13
Hi, just a thought - since 1.9.4 or maybe earlier, I always only replaced the EntityLWC.jar, never the sqlite.jar library. Is there any point in forcing an update to sqlite.jar as well? By removing it, I mean, so that the plugin would copy a fresh one on first load.

**Comment by System-K** [comment] 2018-05-28 15:50
Same issue.

**Comment by Tsuser1** [comment] 2018-08-23 02:04
Please update to the latest build **on my repository of Modern LWC**. Fixed by commit for double door detection.

**Issue closed.**

**Closed by Tsuser1** 2018-08-23 02:04 UTC
Labels: bug, confirmed
