### ISSUE TITLE
Server freezes when doing /lwc admin cleanup

### ISSUE THREAD

**Issue by SFTMedia** [megoesrawr/Modern-LWC#125] opened 2019-05-26 14:31 UTC
**LWC Version (/lwc admin version):** 
2.1.3-dev-c1d515f/ (but happens with older versions too, started happening with 1.13.2)

**Server version (/version):** 
git-Spigot-f09662d-3697519 (MC: 1.13.2)

**Short five word summary of issue:** 
Server freezes when doing /lwc admin cleanup

**Detailed description of problem:**
The server freezes when doing /lwc admin cleanup. It freezes for a long period of time.
NOTE: I am running MariaDB and the SQL server has no issues (I use it for a lot of other things so I would know if it was an issue)

The database isn't that large (attached screenshot of the db in phpmyadmin)
![FXfWvHr](https://user-images.githubusercontent.com/50097524/58383166-09797c00-7fdc-11e9-8549-5938860db525.png)

**Comment by pop4959** [comment] 2019-05-26 18:18
@SFTMedia This repository is dead. Please post the issue at https://github.com/Tsuser1/Modern-LWC/issues.

This might be a duplicate of Tsuser1/Modern-LWC#89.

@Tsuser1 can you close this one too

**Closed** 2019-05-26 18:19 UTC
