### ISSUE TITLE
Down TPS when I put a chest

### ISSUE THREAD

**Issue by TheCalypso** [megoesrawr/Modern-LWC#105] opened 2018-07-16 02:17 UTC
**LWC Version (/lwc admin version):** 2.0.7
**Server version (/version):** 1.12.1

**Short five word summary of issue:** tps down

**Detailed description of problem:** 
Hello, when I have a problem with the lock alone the problem is that if the site quickly enough the server starts as if the plugin could not keep up. It becomes embarrassing because we are ready for 20 players. To help me, I did not change the basic config. Thank you very much !

**If there was an error in console, put it here:** none error just 
```
[03:36:11 INFO]: [LWC] Player created entity [WITHER_SKELETON]
```
But I do not know what that means.

**Comment by megoesrawr** [comment] 2018-08-05 15:36
Try using MYSQL. I dont know why but sqlite is really laggy.

**Comment by Tsuser1** [comment] 2018-08-06 19:45
Well, the problem is SQLite is just ill-suited for this task. I agree, try MySQL and see if that helps with the issues. (Make sure to backup your flatfile database just in case)

**Comment by Tsuser1** [comment] 2018-08-30 06:27
Fixed in latest development builds.

**Issue closed.**

**Closed by Tsuser1** 2018-08-30 06:27 UTC
