### ISSUE TITLE
2.0.5 armorstand errors

### ISSUE THREAD

**Issue by Sikatsu** [megoesrawr/Modern-LWC#82] opened 2018-04-25 11:04 UTC
Error: https://pastebin.com/z13jHjh8

**Comment by Tsuser1** [comment] 2018-04-25 20:00
Duplicate of #81.

**Comment by Sikatsu** [comment] 2018-04-28 09:11
This issue was not fixed.
Error: https://pastebin.com/SesZDBD3

**Comment by theyapps** [comment] 2018-04-28 11:03
And what do you do to trigger this exception?

**Comment by theyapps** [comment] 2018-04-28 18:16
I have confirmed that now locking armor stands does not seem to function. When I marked it complete this was working. I will look into this now.

**Comment by Sikatsu** [comment] 2018-04-28 18:43
I trigger the error using flint from the armorstand editor plugin, I can't
edit armorstands without operator otherwise this error occurs. Did not
happen on 2.0.0

Op za 28 apr. 2018 20:16 schreef Ryan Boykin <notifications@github.com>:

**Comment by theyapps** [comment] 2018-04-28 19:00
@Sikatsu  After I finish fixing this other related issue then I will install armor stand editor and see if I can trigger this exception.

**Comment by Tsuser1** [comment] 2018-08-23 02:03
Caused by another plugin, related to buggy unsupported entity protections.

**Issue closed.**

**Closed by Tsuser1** 2018-08-23 02:03 UTC
Labels: bug, confirmed
